name: Book Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at 3:00 AM UTC
  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:
  scrape-books:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
      - name: Create .env file
        run: |
          echo 'MONGODB_URI="${{ secrets.MONGODB_URI }}"' > .env
          echo 'PORT=5000' >> .env
          
      - name: Install scraper dependencies
        run: |
          cd scraper
          npm install
          
      - name: Run book scraper
        run: |
          cd scraper
          node runScraper.js
          
      - name: Log completion
        run: echo "Scraping completed at $(date)"
